<div class="container">
    <div id="tabs">
        <ul id="tabs">
            <li><a href="#xmlString">Insert XML string</a></li>
            <li><a href="#fileUpload">Upload XML File</a></li>
            <li><a href="/documents">View XML documents</a></li>
        </ul>
        <div id="xmlString">
            <form name="rawXmlForm" method="post">
                <label for="xmlData">Please write or paste your XML data into the text area below</label>
                <textarea name="xmlData" rows="10" cols="50"></textarea>
                <input type="submit" name="btnUploadData" value="Upload data">
            </form>
        </div>
        <div id="fileUpload">
            <form name="xmlFileForm" enctype="multipart/form-data" method="post">
                <label for="xmlFile">Please upload your xml file</label>
                <input type="file" name="xmlFile" />
                <input type="submit" name="btnUploadFile" value="Upload file">
            </form>
        </div>
    </div>
    
    
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>
<script>
    $('div#tabs').tabs();
</script>